In [2]:
import pandas as pd

In [3]:
url = "data/nhanes_2015_2016.csv"
da = pd.read_csv(url)

In [5]:
da['BMXWT'].mean()

np.float64(81.34267560889516)

In [7]:
da['DMDEDUC2'].unique() #categorical ordered

array([ 5.,  3.,  4.,  2., nan,  1.,  9.])

In [8]:
g = da['RIAGENDR'] # categorical unordered
g

0       1
1       1
2       1
3       2
4       2
       ..
5730    2
5731    1
5732    2
5733    1
5734    2
Name: RIAGENDR, Length: 5735, dtype: int64

In [9]:
g.unique()

array([1, 2])

In [11]:
B = ['bird' , 'cat', 'dog' , 'cat' , 'bird' , 'bird']
d = {'categorical' : B}
df = pd.DataFrame(d)

In [ ]:
df

In [13]:
#one hot vector

In [14]:
df_dummies = pd.get_dummies(df['categorical'], prefix = 'category')

In [15]:
df_dummies

category_bird  category_cat  category_dog
0           True         False         False
1          False          True         False
2          False         False          True
3          False          True         False
4           True         False         False
5           True         False         False

In [16]:
df_dummies.values

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False]])